### ISSUE TITLE
Entity picker multiple not working

### ISSUE THREAD

**Issue by tobbbe** [mattbrailsford/umbraco-fluidity#114]
Can only pick one item. Am I missing something?

Settings
![image](https://user-images.githubusercontent.com/2511610/60655905-ce762e00-9e4e-11e9-9ad7-8061d5166914.png)

This happens
![fluid](https://user-images.githubusercontent.com/2511610/60656082-20b74f00-9e4f-11e9-8fe9-1ff26852b586.gif)

**Comment by mattbrailsford** [comment]
@tobbbe have you tried filling in the minimum / maximum number of items allowed in the prevalue? They are empty in your screenshot.

**Comment by tobbbe** [comment]
huh! works if I set "Maximum number of items" to > 1. thanks! :D 

(setting "Minimum number of items" doesnt make it work though)
