### ISSUE TITLE
Multiple Fluidity Tree Items causes dashboard to not show content

### ISSUE THREAD

**Issue by jonrandahl** [mattbrailsford/umbraco-fluidity#59]
I have two tree items set as per the instructions:
`treeConfig.AddCollection<Competition>(...);`
and 
`treeConfig.AddCollection<Entry>(...);`

When I load the section in the back office there is no content in the summary tab?

![2018-06-25_16-50-58](https://user-images.githubusercontent.com/39102/41861240-9c17c540-7898-11e8-9309-eac324630b6c.png)

Steps to reproduce:

1. Create multiple tree items under a single section:
```
  public class FluidityBootstrap : FluidityConfigModule
  {
    public override void Configure(FluidityConfig config)
    {
      config.AddSection("Competitions", "icon-trophy", sectionConfig =>
      {
        sectionConfig.SetTree("Competitions", treeConfig =>
        {
          treeConfig.AddCollection<Competition>(c => c.Id, "Competition", "Competitions", "A listing of competitions held", "icon-medal", "icon-medal", collectionConfig =>
            {
              ...
            });
          treeConfig.AddCollection<Entry>(e => e.Id, "Entry", "Entries", "A list of entries to the competitions", "icon-poker-chip", "icon-poker-chip", collectionConfig =>
            {
              ...
            });
        });
      });
    }

  }

```

2. Open the section in the back office.

**Comment by mattbrailsford** [comment]
Hi Jon,

This is expected behaviour as the summary dashboard only shows collections for which `ShowOnDashboard` has been set to `true` so out of the box it will be empty.

**Comment by jonrandahl** [comment]
So I need to add `collectionConfig.ShowOnDashboard();` to the collections I want to show there ... got it!!!

![2018-06-25_17-46-29](https://user-images.githubusercontent.com/39102/41863787-c45fbe16-789f-11e8-8f20-51b750f5f49e.png)

**Comment by mattbrailsford** [comment]
That is correct yes
