### ISSUE TITLE
Hide option to remove on Entity Picker?

### ISSUE THREAD

**Issue by tcmorris** [mattbrailsford/umbraco-fluidity#60]
Hi team,

I've been looking through Fluidity and figuring how I'd like to use it. One of the scenarios that I came across is for relations where one entity (e.g. customer) might have a picker for another entity (e.g. order). 

The entity picker does just that, but if it's an existing relationship, I'd like to enforce this so that it cannot be removed by an editor. I thought maybe the ReadOnly option would fit, but it'd be good for a new one to be chosen or to go through and edit the properties on the linked entity and with ReadOnly you only get a label.

So, I was thinking that we can make the `allow-remove` configurable on the entity picker. For backwards compatibility it would need to be a hide option so existing pickers still worked as before, and then we'd have the option to disable.

What do you think? Happy to make the change.

**Comment by mattbrailsford** [comment]
Fixed in merge PR  #64

Thanks @tcmorris
