### ISSUE TITLE
More granular control over CRUD options

### ISSUE THREAD

**Issue by tcmorris** [mattbrailsford/umbraco-fluidity#61]
Hi team,

Currently, it is possible to either have CRUD options or disable them via the `MakeReadOnly` method. Therefore, making CRUD all or nothing. It would be good if there were options to disable create, but enable read and update for example.

Not sure where to pick up the code exactly, just raising the idea. Let me know, happy to take a look into it.

**Comment by mattbrailsford** [comment]
Closing this issue. Can continue the discussion on the open PR #75
