### ISSUE TITLE
Is't possible to use data retrieved from Fluidity into Umbraco document type and API?

### ISSUE THREAD

**Issue by biapar** [mattbrailsford/umbraco-fluidity#76]
Is't possible to use data retrieved from Fluidity into Umbraco backend ( for example into a document type ) and API ( alternative via PETA POCO )?

**Comment by mattbrailsford** [comment]
If you need to link to an entity in umbraco then fluidity comes with an entity picker property editor you can configure. Docs here https://umco.github.io/umbraco-fluidity/property-editors/entity-picker/

In terms of accessing data directly from Fluidity repositories then you can do that also. Docs here https://umco.github.io/umbraco-fluidity/api/repositories/#accessing-a-repository-in-code

**Comment by mattbrailsford** [comment]
Question answered so closing issue
