### ISSUE TITLE
two bugssies fluidity wwebsite

### ISSUE THREAD

**Issue by teusch** [mattbrailsford/umbraco-fluidity#8]
![image](https://user-images.githubusercontent.com/5502583/31950249-7e5ae514-b8db-11e7-90d5-bd240049bef5.png)
![image](https://user-images.githubusercontent.com/5502583/31950306-9bbdd256-b8db-11e7-8c3a-9cec23aa66c8.png)

**Comment by mattbrailsford** [comment]
Thanks for reporting. I've fixed the spelling mistake, but the nav isn't quite a bug. It's just that I haven't released the package yet so I haven't setup the umbraco url yet. This should all hook up once it' actually released. Thanks for reporting though.
