### ISSUE TITLE
Using DocTypes as templates?

### ISSUE THREAD

**Issue by YodasMyDad** [mattbrailsford/umbraco-fluidity#83]
Might be an odd question. But how much extra work do you think it would take for Fluidity to be able to mix a DocType along with custom fields?

So, I would set up my first tab with custom fields and name the tab (i.e. Product), then I want to choose a DocType as the template for the rest. If that DocType has three tabs (One, Two, Three), they are rendered after the ‘Product’ tab, so I have four tabs. 

Then I can save the values of all those fields to a database.

**Comment by mattbrailsford** [comment]
It's possible I guess. Could have something like `editorConfig.FromContentType("contentTypeAlias")`.

This would have to make some assumptions though a) all your propertyAliases should directly match your model b) You don't need to do any custom mapping c) you don't need to set any default values. Essentially, you'd bypass the whole mapping for the editor completely.

Interesting idea 🤔

**Comment by mattbrailsford** [comment]
RE the assumptions, I guess you could have a more in-depth API for this kinda like automapper:

````
editorConfig.FromContentType("contentTypeAlias")
    .ForProperty("alias").SetValueMapper<MyValueMapper>()
````

**Comment by mattbrailsford** [comment]
Some other thoughts:
* The mapping + the doc type are seperate so it could feel dis-jointed
* Fluidity creates and stores the config at app startup so basing on doctype could cause syncing issues if the doctype is changed

**Comment by mattbrailsford** [comment]
Not something I plan to look at as a feature so closing issue.
