### ISSUE TITLE
Do we know if this will this work with v8

### ISSUE THREAD

**Issue by YodasMyDad** [mattbrailsford/umbraco-fluidity#84]
I know its early to ask this, but wondering if you've seen (or heard) of any breaking changes with what you have done?

**Comment by mattbrailsford** [comment]
@YodasMyDad I haven't tried it yet, but I'm expecting that it will break. The UI is tied quite heavily to the Umbraco angular directives which I'm guessing many will have changed and the save pipeline mocks the umbraco content saving pipeline so if that has changed, then that will also have an effect.

**Comment by mattbrailsford** [comment]
Question answered so closing issue.
