### ISSUE TITLE
Dynamic data types

### ISSUE THREAD

**Issue by ThomasBleijendaal** [mattbrailsford/umbraco-fluidity#85]
Hi @mattbrailsford,

When I have an entity which contains a enum (example, PhaseType), I currently have to create a custom DataType in Umbraco ("PhaseTypePicker"), to which I have to configure all the enum options as pre-values, and then do the mapping from pre-value id to the corresponding enum option. This is tedious and quite brittle. 

How would you feel about having a feature in Fluidity which recognizes which enum is used for a field, and generates a dropdown editor with the correct pre-values on the fly? It would still use all the default UI from Umbraco, but without having the user specify a DataType.

**Comment by mattbrailsford** [comment]
Hmm, in this situiation, I would probably use something like nuPickers which has build in Enum based data sources. You'd still need to configure a Data Type, but would at least save you from having to manage the dropdown options.

It's an interesting one, and I'm not totally averse, but I don't think it's 100% as simple as it sounds. For example, an Enum can use the `[Flags]` attribute to support chaining like `MyEnum.Opt1 | MyEnum.Opt2`, in this situation, would you want a dropdown? or maybe a checkbox list? or maybe a multi-list? This is kinda why I like to leave it to the config and use core data types. Nothin "Magical" happens then as I think as soon as we introduce "Magic" it might start to get confusing.

As an initial answer then, do you think using nuPicker with Enum data source saves you enough tedium to be a valid answer?

**Comment by ThomasBleijendaal** [comment]
I think that for now nuPickers is probably good enough. This solves the issue of having to manage dropdown options. I agree that it would not be simple to start supporting such things in Fluidity. It probably best to have other packages provide this sort of functionality, and allow for easy integration in Fluidity via data types.
