### ISSUE TITLE
Allow editing, but not delete/create

### ISSUE THREAD

**Issue by tobbbe** [mattbrailsford/umbraco-fluidity#89]
How to completely disable delete/create of entities, but still allow editing of the properties?
So like `MakeReadOnly()` but allow editing of properties

`Fluidity.Fluidity.DeletingEntity += (sender, args) => {
                args.Cancel = true;
            };` prevents entities to be deleted, but they are removed from the UI (sidebar list) until reload and the page reloads.

![flu](https://user-images.githubusercontent.com/2511610/51994744-bbcb8780-24b1-11e9-8cf3-011e898337b4.gif)

**Comment by mattbrailsford** [comment]
Will be resolved by PR #75. Closing issue, can continue discussion on the PR
