### ISSUE TITLE
Cannot read property 'defaultOrderBy' of null

### ISSUE THREAD

**Issue by tobbbe** [mattbrailsford/umbraco-fluidity#90]
Im trying to have an Entity picker as datatype on a fieldConfig (`fieldConfig.SetDataType("GboxArticleCategoryPicker");`). But im getting a js-error when clicking on the Add-button. Any idea why?

![image](https://user-images.githubusercontent.com/2511610/53425630-ad578980-39e5-11e9-9f4c-514be7ab337d.png)

**Comment by mattbrailsford** [comment]
@tobbbe you might want to enable debug mode in web.config so that the JS error gives you some better information, rather than it just pointing to client dependency.

**Comment by skartknet** [comment]
I'm having this same issue. The problems is coming from entitypicker.controller.js:56

`$scope.listView.options.defaultOrderBy = collection.listView.defaultOrderBy;`

collection.listView is null. Am I missing something?
