### ISSUE TITLE
Missing { in code example

### ISSUE THREAD

**Issue by Migaroez** [mattbrailsford/umbraco-fluidity#91]
![image](https://user-images.githubusercontent.com/6025797/53484630-8dc36e00-3a84-11e9-9e15-ffb8825b05ab.png)

**Comment by mattbrailsford** [comment]
I'd sure appreciate a PR?

**Comment by Migaroez** [comment]
Also lower in the example it says void void
![image](https://user-images.githubusercontent.com/6025797/53484770-dc710800-3a84-11e9-92a1-4ae85ec1a4dd.png)

**Comment by Migaroez** [comment]
> I'd sure appreciate a PR?

Ill try and get on that later today :)

**Comment by mattbrailsford** [comment]
> Ill try and get on that later today :)

That would be awesome. Thanks 👍

**Comment by mattbrailsford** [comment]
Fixed in merged PR #92 

Thanks @Migaroez :+1:
