### ISSUE TITLE
Exception When Name Property Has Null Value

### ISSUE THREAD

**Issue by Nicholas-Westby** [mattbrailsford/umbraco-fluidity#96]
Configure Fluidity to work against a database table. When configuring the collection, set a name property:

```c#
collection.SetNameProperty(y => y.Name);
```

If that name property ever has a null value, an exception will be thrown when viewing the list view for the collection in the back office. It seems this happens because of this code in Fluidity:

```c#
name = entity.GetPropertyValue(collection.NameProperty).ToString();
```

It gets the property value and then calls `.ToString()` on it, which bombs out when the value is null.

I will submit a pull request for this momentarily.

**Comment by mattbrailsford** [comment]
I've merged in the PR to act as a safety check, but really, fluidity requires a name field. If your configured name field has the possibility of being null, I suggest you either use a result column to return a "display value" should the real name property be null, or use `SetNameFormat` to do this dynamically at runtime instead.

    collectionConfig.SetNameFormat(r => r.Name ?? "Anonymous")
